Breakthrough-Energy/PreREISE

prereise/gather/demanddata/nrel_efs/map_states.py
prereise/gather/demanddata/nrel_efs/tests/test_aggregate_demand.py
prereise/gather/hydrodata/eia/decompose_profile.py
prereise/gather/hydrodata/eia/tests/test_decompose_profile.py
prereise/gather/hydrodata/eia/tests/test_interpolate_capacity_factors.py
prereise/gather/tests/test_helpers.py
tox.ini

We can take advantage of isort's built in "profile" for black compatibility. This includes a line length option which we were msising, along with a couple others I'm not sure about. [Source](https://github.com/PyCQA/isort/blob/develop/isort/profiles.py) from their repo is easy to read.
Added isort section in tox.ini
Ran `tox -e format` locally, and ci passes.
5 min

ci: use black profile for isort

---

.github/workflows/lint.yml
.github/workflows/test.yml

Add PR trigger to support forked repositories. Turns out this is not a security concern, as actions triggered by external PRs run in a limited security context. Some details [here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request), and [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).
Will have to merge to actually test this.
5 min

ci: enable PR trigger

---

.github/workflows/lint.yml
prereise/gather/demanddata/nrel_efs/tests/test_aggregate_demand.py
prereise/gather/hydrodata/eia/tests/test_net_demand.py
prereise/gather/request_util.py
prereise/gather/solardata/ga_wind/ga_wind.py
prereise/gather/solardata/nsrdb/nrel_api.py
prereise/gather/solardata/nsrdb/sam.py
prereise/gather/solardata/tests/test_pv_tracking.py
prereise/gather/tests/test_helpers.py
prereise/gather/winddata/rap/noaa_api.py
prereise/gather/winddata/rap/rap.py
prereise/gather/winddata/rap/tests/test_power_curves.py
tox.ini

Add flake8 to linting workflows, as we have in other packages. Configuration in tox.ini is similar to elsewhere, but also excluding notebook files which exist locally, but outside of git. 
* Add flake8 option and configuration to tox.ini 
* Configured github action to run flake8, via tox
* Fixes to source files, mainly unused imports and variables
tox
10 min

ci: add flake8 and fix warnings

---

prereise/gather/demanddata/nrel_efs/tests/test_get_efs_data.py

The goal of this PR is to speed up the NREL EFS data download and extraction tests. Due to the size of the .zip files, the tests take minutes to run (as opposed to the other tests that take seconds). See #145 for reference.
`test_get_efs_data.py` was updated to not test `download_demand_data` and `download_flexibility_data` individually, but rather to test the individual private functions (e.g., `_download_data`, `_extract_data`) that comprise them. While testing the private functions create some more tests, they are much faster because `_download_data` can be tested with a much smaller file (the same can't be done with `download_demand_data` and `download_flexibility_data` since they are created to only download and extract the large NREL EFS data sets).
All of the changes are contained …

test: make NREL EFS download tests faster

---

prereise/gather/request_util.py
prereise/gather/tests/test_retry.py

We set an attribute on the function to retry which, initially for debugging, also enabled continuation in downloading wind data despite reaching the max attempts. However, it needs to be set on the wrapped function rather than the `func` object passed in, otherwise the decorated function won't be accessing the same value being incremented by the retry wrapper. 
Set the attribute on the right object, add a test to simulate the current usage.
Added new unit test
5 min

fix: set attribute on wrapped function so it actually works

---

prereise/gather/demanddata/eia/clean_data.py
prereise/gather/solardata/nsrdb/sam.py
prereise/gather/winddata/rap/power_curves.py
prereise/gather/winddata/rap/tests/test_power_curves.py
tox.ini

Add pep8-naming check to flake8, so it is run by tox locally and in github. 
See https://github.com/Breakthrough-Energy/RenewableEnergyProject/issues/343 (not sure how else to link this)
In this case, we only had to ignore one warning, everything else is just switching to snake_case. 
`tox -e flake8`
5 min

ci: add pep8-naming to flake8 and fix warnings

---

.coveragerc
.github/workflows/test.yml
Pipfile
Pipfile.lock
pytest.ini
requirements.txt

Identical to Breakthrough-Energy/PowerSimData#471 except didn't add python 3.9 testing since pyproj is incompatible, so will address that separately.
One thing to note - I was having issues related to nrel-pysam when regenerating the lock file, so I upgraded to the latest, which is within the same major version. Haven't checked the impact of that yet.

ci: add coverage report to pytest

---

prereise/gather/demanddata/nrel_efs/tests/test_get_efs_data.py
pytest.ini

Use `pytest` marker to deselect test fetching third party data
There is no code
Test is deselected when `tox pytest-local` (equivalent to `pytest -m 'not integration'`) is invoked
I imported `pytest` and mark `test_download_data` as being an integration test
N/A
2min

Use integration marker for test fetching data

---

.coveragerc
.github/workflows/coverage.yml
.github/workflows/packages.yml
README.md
tox.ini

Plumbing for reporting code coverage to codecov.io.
* Add separate github workflow, to run on merges to develop
* Parameterize `pytest-local` tox env so we can specify the xml format required by codecov
* Add dependencies label to packages.yml (unrelated, but trivial)
* Include tests in the coverage measurement
* add some missing badges
Ran the workflow to initialize the repository on codecov and generate the badge.
5 min

Report code coverage

---

prereise/gather/tests/test_retry.py

The latest release of pep8-naming now includes N818 which checks the naming of `Exception` subclasses.
Fix the one existing violation .
`tox -e flake8`
1 min

chore: fix N818 warning from pep8-naming

---

ATTRIBUTION.md

Create folder structure and update **ATTRIBUTION.md**. HIFLD files have been uploaded to the BES blob storage.
N/A
N/A
* Formatted a previous entry
* 3 new entries for HIFLD data (transmission, substation and generation)
N/A
10min

Folder structure an ATTRIBUTION file

---

prereise/cli/data_sources/__init__.py
prereise/cli/data_sources/data_source.py
prereise/cli/data_sources/demand_data.py
prereise/cli/data_sources/exceptions.py
prereise/cli/data_sources/hydro_data.py
prereise/cli/data_sources/tests/test_demand_data.py
prereise/cli/data_sources/tests/test_hydro_data.py

What is the larger goal of this change?
This is the last planned part of the [download manager project](https://breakthrough-energy.github.io/docs/communication/project_ideas.html#project-1a-download-manager). As per discussion with @rouille and @BainanXia, demand data and hydro data is very complex and a very manual process to generate. In addition, most of the data is already downloaded and available locally, so there's no data to download. This PR adds two stub classes for demand and hydro data for completion sake
How is the purpose executed?
Two stub classes for hydro and demand data are created that simply raise exceptions. Classes can be filled in in the future if process of gathering …

feat: add stubs for demand and hydro data cli

---

prereise/gather/griddata/hifld/data_access/load.py

Load HIFLD data. The `ben/read` branch has been branched off `ben/const` that is is under review (#194)
For each of the 5 HIFLD, the file is loaded and filtered. The user defined table enclosing the information on the load zone is also loaded.
Manual testing, e.g.:
```
>>> from prereise.gather.griddata.hifld.data_access.load import get_hifld_electric_power_transmission_lines_topology
>>> topology = get_hifld_electric_power_transmission_lines_topology("https://besciences.blob.core.windows.net/datasets/hifld/Electric_Power_Transmission_Lines_Jul2020.geojson.zip")
>>> type(topology)
<class 'list'>
>>> len(topology)
71554
>>> from prereise.gather.griddata.hifld.data_access.load import …
```

Load HIFLD data

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_process/transmission.py

Implement initial filtering of transmission lines and substations, following the lead from @LFPower, @terrywqf, and @Mingze-Li128.
- `build_transmission` is the main user-facing function, which kicks off several lower-level functions in turn. This will eventually produce the final transmission network topology (substations, buses, branches), although this PR does not go that far.
- `get_substations_with_nonzero_lines` filters based on the `LINES` column of the substation table (as done in the `clean` function of @Mingze-Li128's branch).
- `check_for_location_conflicts` checks for any substations with duplicate lat/lon pairs.
- `filter_lines_with_unavailable_substations` looks for lines for …

feat: add functions to perform transmission line filtering

---

prereise/gather/griddata/hifld/data_process/transmission.py

Speed up the substation matching/distance function introduced in #199 and modified in #202. No change in logic, just in implementation.
Within `filter_lines_with_nonmatching_substation_coords` we call `find_closest_substation_and_distance` N times, where `N` is the number of lines.
- Before: In each call to `find_closest_substation_and_distance` we filter the entire substations dataframe to find substations with a given name.
- After: within `filter_lines_with_nonmatching_substation_coords` we group the substations by name once, and then within `find_closest_substation_and_distance` we just call `get_group` on the already-grouped-by-name substations `GroupBy` object.
I would expect that …

refactor: use groupby to speed up distance calculations

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_access/load.py
prereise/gather/griddata/hifld/data_process/tests/test_transmission.py
prereise/gather/griddata/hifld/data_process/transmission.py

Within the raw HIFLD data, there are many transmission lines with unknown voltages. Per #205, we need to determine a voltage for each transmission line in order to be able to create buses within substations. This is an attempt to create a process that fulfills this requirement, and currently achieves 100% coverage on the largest connected component.
~We create a new helper function `safe_get_group`, which can be used to call `get_group` on a pandas `GroupBy` object and has a default behavior if the key is not present. This is used within the new `augment_line_voltages` function to improve computational performance.~ EDIT: this function is no longer necessary and has been removed.
All new …

feat: add function to infer line voltages

---

prereise/gather/griddata/hifld/data_process/tests/test_transmission.py
prereise/gather/griddata/hifld/data_process/transmission.py

Address #205 by starting the bus data frame. ~This PR depends on #208, which is why it is currently listed as the PR target (so that only the changes since then are shown), but this PR will eventually target the `hifld` branch.~ EDIT: #208 has been merged, so this targets `hifld` now.
- The `lines` and `substations` data frames are used to identify the set of voltages attaches to each substation.
- This set is exploded to yield a Series entry for (substation, voltage) combination.
- The index is set to be a column, then this column is popped out to the data frame to become the `bus2sub` mapping.
A unit test has been added to demonstrate/verify the functionality on a simple test case.
We can …

feat: add function to create buses from substations and lines

---

prereise/gather/griddata/hifld/data_process/tests/test_transmission.py
prereise/gather/griddata/hifld/data_process/transmission.py

Closes #206. ~This is a draft PR right now, since it relies on code from #210. It could also become part of #210.~
Using buses, grouped by substation, for each substation with more than one bus, a transformer is added between the highest-voltage bus in the substation and each other bus. This is an arbitrary topology that seems reasonable enough, although it is by no means the best one.
A new unit test is added which covers the bases of: no transformers within a substation, one transformer within a substation, multiple transformers within a substation.
```python
>>> from prereise.gather.griddata.hifld.data_process.transmission import (
...     build_transmission,
...     create_buses,
... …
```

feat: add function to create transformers within substations

---

prereise/gather/griddata/hifld/data_access/load.py

Switch [(lon, lat), (lon, lat), ..] points to [(lat, lon), (lat, lon), ...] when we load coordinates, to match our convention in the rest of the codebase. See conversation at https://github.com/Breakthrough-Energy/PreREISE/pull/219#discussion_r707615437
It's a fancy one-liner, applied to each coordinates list in the data frame. The inner-most `list`/`zip` pair collects the `[(lon, lat), (lon, lat), ..]` points as `[(lon, lon, ...), (lat, lat, ...)]`, then this 2-length list is reversed, and the outer-most `list`/`zip` re-expands to `[(lat, lon), (lat, lon), ...]`. A simple example:
```python
>>> a = [(1, 2), (3, 4), (5, 6)]
>>> list(zip(*list(zip(*a))[::-1]))
[(2, 1), (4, 3), (6, 5)]
``` …

refactor: switch (lon, lat) points to (lat, lon)

---

prereise/gather/griddata/hifld/data_process/transmission.py

This is a follow-up to #223. Now that we have points as (lat, lon) instead of (lon, lat), we need to change the code that uses coordinates.
Undoing the list reversal `[::-1]`.
Manually.
Before, all lines are dropped because they're evaluated as 'mismatches', since the (lat, lon) location is very far away from the (lon, lat) location:
```python
>>> from prereise.gather.griddata.hifld.data_process.transmission import build_transmission
>>> lines, substations = build_transmission()
dropping 6892 substations of 70857 total due to LINES parameter equal to 0
dropping 759 lines with one or more substations listed as 'NOT AVAILABLE' out of a starting total of 71554
dropping 3143 lines with one or …
```

refactor: change transmission processing code to expect (lat, lon) instead of (lon, lat)

---

prereise/gather/griddata/hifld/data_process/transmission.py

Select HIFLD substations based on HIFLD lines
* `map_lines_to_substations_using_coords`: create a data frame mapping lines to substations base on coordinates
* `assign_substations_to_lines`: update `lines` and `substations` data frames. In particular: 
* update *SUB_1* and *SUB_2* columns in `lines` data frame (name of selected `substations` are used) 
* new *SUB_1_ID*, *SUB_2_ID* columns giving the selected substation ID
* new *OTHER_SUB_1_ID* and *OTHER_SUB_2_ID* indicating other candidates at same endpoint, either a substation, tap, riser or dead end
* `build_transmission`: the function has been updated to use the above method to get the lines/substations tuple
How did you test this change …

feat: add transmission to substation track selection

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_access/load.py
prereise/gather/griddata/hifld/data_process/generators.py
setup.cfg

Add code to estimate heat rate curves from EPA AMPD data. See #222 for more context.
- Within **load.py**, we add a new function `get_eia_epa_crosswalk` to get the EIA/EPA crosswalk CSV as a dataframe with columns interpreted properly. We also modify the `get_epa_ampd` function to only use a subset of columns, to be able to cut down on the large memory requirements for loading all of the EPA data into memory.
- Within **generators.py**, we add a new primary function `estimate_heat_rate_curve`. Within this function, we check if there is an EIA/EPA crosswalk mapping available, and if there are enough non-null data points available to fit a curve to (if no to either, return NA). If so, we use …

feat: add heat rate parameter estimation

---

prereise/gather/griddata/hifld/data_process/tests/test_topology.py
prereise/gather/griddata/hifld/data_process/topology.py
prereise/gather/griddata/hifld/data_process/transmission.py

Inspired by finding closest neighbor using KDTree data structure will improve the computational performance when working with big candidate sets, discussing with @rouille and @danielolsen, there might be a chance of improving the computational time of generating the MST using the same logic. In the original implementation, during the exhaustive search of the shortest link between two islands, we did loop through the list of potential candidates each time, now we build a KDTree for the bigger island in each pair in the combination, then query each point within the small island in the tree to find the closest neighbor.
In general, KDTree should outperform over the naive implementation for big …

feat: add options to use KDTree in connecting islands by MST

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_process/transmission.py

Partial fulfilment of #233: this addresses the HVDC transmission lines within the HIFLD dataset, but does not yet address the B2Bs, which will require a different method of splitting substations into sub-substations for each interconnection.
In **const.py**, ratings are added for DC lines with known capacities.
In **transmission.py**:
- A small helper function `split_lines_to_ac_and_dc` is added to filter out DC lines via some combination of the `TYPE` attribute of the HIFLD dataset and manually specified indices.
- `build_transmission` uses this function, then adds impedances and AC ratings to AC branches only (using functionality introduced in #218 and #219), and uses the pre-defined …

feat: filter DC lines out of AC transmission network processing within HIFLD construction

---

ATTRIBUTION.md
prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_access/load.py
prereise/gather/griddata/hifld/data_process/demand.py

Estimates population per substation, using data from simplemaps.com, and uses this information to add demand to buses. This is a re-implementation of the approach taken by the collaborators. Closes #229. 
We add a new module `prereise.gather.griddata.hifld.data_process.demand` with a single function `assign_demand_to_buses`. This function:
1. Loads population by ZIP and by county from CSVs in the repo.
2. Sorts substations by connected transmission capacity.
3. Distributes each ZIP code's population to the N highest-transmission-capacity non-generation substations within that ZIP, where N is an integer value less than the total (calculated using the `substation_load_share` fraction within …

feat: add function to assign demand to buses proportional to population

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data_access/load.py
prereise/gather/griddata/hifld/data_process/tests/test_transmission.py
prereise/gather/griddata/hifld/data_process/transmission.py

Various fixes for processing of HIFLD transmission data:
- Correct a lat/lon vs. lon/lat issue (and add a test for said issue) when mapping lines to substations
- In addition to lines whose status is `IN SERVICE`, also return lines whose status is `NOT AVAILABLE`, since this represents most of the lines in the Rocky Mountain states (see https://github.com/Breakthrough-Energy/PreREISE/issues/233#issuecomment-960081829).
- Using a rough bounding box of the contiguous U.S., don't return lines for which at least one end is outside of this box (e.g. Alaska, Hawaii, Puerto Rico)
- Ensure that indices aren't duplicated within the branch dataframe as a results of concatenating individual dataframes …

fix: various issues with HIFLD transmission loading/processing

---

prereise/gather/griddata/hifld/const.py
prereise/gather/griddata/hifld/data/zone.csv
prereise/gather/griddata/hifld/data_access/load.py
prereise/gather/griddata/hifld/data_process/topology.py
prereise/gather/griddata/hifld/data_process/transmission.py

- Load substations whose status is either `IN SERVICE` or `NOT AVAILABLE`. Although `NOT AVAILABLE` substations are only about 5% of the total, they're about 20% of the substations within Texas and New Mexico, which causes lines to get mapped to faraway substations which are sometimes in other interconnections.
- Add a function which can separate and label the `interconnect` attribute of lines and substations, given input on where to split the substations and how to re-join them.
- Add data that when input into the new function, splits the HIFLD network into three interconnections. This data is imperfect, especially regarding the Eastern/ERCOT seam around Lubbock and the Texas panhandle more …

feat: separate interconnections via network topology

---

prereise/gather/demanddata/eia/tests/test_map_ba.py

Disable tests of functions that rely on the geo.fcc.gov API, which has been failing with `502 Bad Gateway` for several days now.
Skipping tests.
Didn't test 🙃.
30 seconds.

chore: disable tests for failing geo lookup API

---

prereise/gather/demanddata/transportation_electrification/data_process.py

What is the larger goal of this change?
To add the data processing script that will organize the NHTS data.
How is the purpose executed?
This code filters through the NHTS data based on the inputted census division and reorganizes the information. It also calculates additional information based on the given data.
How did you test this change (unit/functional testing, manual testing, etc.)? 
This was tested through manual testing using data from "trippub.csv".
* It's helpful to clarify where your new code lives if you moved files around or there could be confusion/
The new code is located at "PreREISE/prereise/gather/demanddata/transportation_electrification/data_process.py"
* What files are …

feat: adding data processing script

---

prereise/gather/winddata/const.py
prereise/gather/winddata/hrrr/calculations.py
prereise/gather/winddata/hrrr/tests/test_calculations.py
prereise/gather/winddata/impute.py
prereise/gather/winddata/power_curves.py
prereise/gather/winddata/rap/rap.py
prereise/gather/winddata/tests/test_power_curves.py

This partially addresses #213 by decoupling the HRRR wind profile creation from the Grid object and associated network-specific mappings. Instead of assuming that the dataframe passed is from the `usa_tamu` grid, and using the zone-id-to-state-abbreviations from that grid model, we expect a dataframe with a `state_abv` column. This is simpler than what we need for #247, since we don't do interconnection-level blending for states without entries in the EIA wind data table (and therefore don't need grid-level data); we just need the state abbreviation for each wind farm.
This also introduces a new wind profile generation function which uses the individual attributes of each wind farm, since we …

refactor/feat: decouple HRRR wind profile generation from Grid object, add individual calculation
